In [2]:
##1. Import the numpy package under the name np

In [3]:
import numpy as np

In [4]:
##2. Print the numpy version and the configuration

In [5]:
print(np.__version__)
np.show_config()

2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [6]:
#3. Create a null vector of size 10

In [7]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
#4. How to find the memory size of any array

In [9]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [10]:
#5. How to get the documentation of the numpy add function from the command line? 

In [11]:
import numpy as np
np.info(np.add)




add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [12]:
#6. Create a null vector of size 10 but the fifth value which is 1

In [13]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [14]:
#7. Create a vector with values ranging from 10 to 49

In [15]:
arr=np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#8 Reverse a vector (first element becomes last)

In [17]:
arr=np.arange(10, 50)
reversed_arr=arr[::-1]
print(reversed_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
#9 Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
import numpy as np
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]

In [21]:
arr=np.array([1, 2, 0, 0, 4, 0])
indices=np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


In [22]:
#11 Create a 3x3 identity matrix 

In [23]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#12. Create a 3x3x3 array with random values 


In [25]:
random_array=np.random.random((3, 3, 3))
print(random_array)

[[[0.14600704 0.95539564 0.66784152]
  [0.74717937 0.5944269  0.21802512]
  [0.04676505 0.96680018 0.33163647]]

 [[0.35158285 0.97419527 0.60819795]
  [0.67077744 0.53356113 0.30497771]
  [0.66124561 0.92690959 0.20164872]]

 [[0.41791159 0.95493458 0.44100456]
  [0.77817459 0.5654851  0.92186477]
  [0.50823872 0.37434853 0.01810508]]]


In [26]:
#13.Create a 10x10 array with random values and find the minimum and maximum values 

In [27]:
random_array=np.random.random((10, 10))
min_num=np.min(random_array)
max_num=np.max(random_array)

print(random_array)
print("Minimmum value:", min_num)
print("Maximum value:", max_num)

[[0.96748633 0.32550686 0.64050316 0.7794235  0.95192905 0.6697375
  0.34988534 0.75893515 0.16915901 0.18405422]
 [0.95867498 0.61504538 0.51445703 0.99449868 0.68661721 0.66788427
  0.23847827 0.27459288 0.36573477 0.34971087]
 [0.29309747 0.96741513 0.19162573 0.3259644  0.5971358  0.58286952
  0.18423986 0.6101316  0.80639665 0.62030559]
 [0.98883553 0.19212146 0.32523306 0.64722768 0.89846571 0.6308224
  0.16964214 0.98034537 0.94262788 0.10433171]
 [0.35873024 0.68858395 0.38289653 0.25676251 0.66757046 0.59747758
  0.60615088 0.17393958 0.79667669 0.28367601]
 [0.82647414 0.5726718  0.44813295 0.70814517 0.93083283 0.98619704
  0.56807583 0.87971696 0.35386346 0.06999517]
 [0.69204096 0.78957292 0.80797309 0.92262536 0.06654566 0.0608622
  0.76736554 0.95617188 0.26236989 0.65666756]
 [0.75021849 0.81139109 0.26896291 0.46446022 0.91656131 0.79206374
  0.91072734 0.78442876 0.44249014 0.25442327]
 [0.91815426 0.06400748 0.1159816  0.12881257 0.1798273  0.66184223
  0.67795072 0.

In [28]:
#14. Create a random vector of size 30 and find the mean value

In [29]:
random_vector=np.random.random(30)
mean_value=np.mean(random_vector)

print("Random Vector: \n", random_vector)
print("\nMean Value:", mean_value)

Random Vector: 
 [0.92150761 0.60624905 0.24944348 0.95564181 0.7827756  0.09434598
 0.11539273 0.50509893 0.35323458 0.83121824 0.23771061 0.86605477
 0.63454225 0.84489526 0.00650894 0.14265627 0.2586455  0.89308819
 0.66233498 0.91298792 0.44338583 0.53034497 0.72778238 0.26699401
 0.92403913 0.35165967 0.02186847 0.3662103  0.39598754 0.29252581]

Mean Value: 0.5065043592520263


In [30]:
#15.Create a 2d array with 1 on the border and 0 inside 

In [31]:
rows, cols=10, 10
array=np.zeros((rows, cols), dtype=int)

array[0, :]=1
array[-1, :]=1
array[:, 0]=1
array[:, -1]=1

print(array)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [32]:
#16 How to add a border (filled with 0's) around an existing array? 

In [33]:
import numpy as np
arr =np.ones((3, 3), dtype=int)
border_arr=np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(border_arr)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [34]:
#17What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [ ]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [37]:
matrix=np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [38]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern 


In [39]:
matrix=np.zeros((8, 8), dtype=int)

matrix[1::2, ::2]=1
matrix[::2, 1::2]=1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [43]:
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function 

In [44]:
pattern=np.array([[0, 1], [1, 0]])
checkboard=np.tile(pattern, (4, 4))
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#22. Normalize a 5x5 random matrix 


In [45]:
a=np.random.random((5,5))
a=(a-np.mean (a)) / (np.std (a))
print(a)

[[-0.18333084 -1.4570962   0.81632033  0.06647353  1.76419965]
 [-0.77357338 -0.01081339 -0.86147958 -0.21754898 -1.29167363]
 [ 1.40935453  0.08666371 -0.48732666 -0.55081234  1.12157395]
 [-0.94325346  1.73686737  0.42963542  2.19928352 -1.12448231]
 [-0.56396583 -0.74999307 -0.29015594  0.66081303 -0.78567944]]


In [ ]:
 #23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [49]:
color = np.dtype([("r", np.ubyte, 1), 
                  ("g", np.ubyte, 1), 
                  ("b", np.ubyte, 1), 
                  ("a", np.ubyte, 1)])
colors = np.array([(255, 0, 0, 255),
                   (0, 255, 0, 255),
                   (0, 0, 255, 128)],
                  dtype=color)
print(colors)



[([255], [  0], [  0], [255]) ([  0], [255], [  0], [255])
 ([  0], [  0], [255], [128])]


In [ ]:

#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)


In [51]:
Ch=np.random.random((5,3))
I=np.random.random((3,2))
N=np.dot(Ch, I)
print(N)

[[0.6381198  0.59404198]
 [0.42407398 0.4753872 ]
 [0.72013323 1.06165569]
 [0.45087721 0.79164163]
 [0.67570107 0.67606287]]


In [ ]:
 #25 Given a 1D array, negate all elements which are between 3 and 8, in place

In [53]:
arr=np.array([1, 3, 4, 6, 7, 9, 10])
arr[(arr>3) & (arr<8)] *=-1
print(arr)

[ 1  3 -4 -6 -7  9 10]


In [54]:
#26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [56]:
#Consider an integer vector Z, which of these expressions are legal?


In [57]:
Z = np.array([1, 2, 3, 4])
print(Z ** Z) 


[  1   4  27 256]


In [58]:
Z = np.array([1, 2, 3, 4])
print(2 << Z >> 2) 

[1 2 4 8]


In [ ]:
#28. What are the result of the following expressions

In [59]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\user\AppData\Local\Temp\ipykernel_85208\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_85208\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_85208\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [ ]:
#29. How to round away from zero a float array ?

In [60]:
arr=np.array([-1.5, -2.3, 0.2, 3.7, 4.5])
rounded_arr=np.copysign(np.ceil(np.abs(arr)), arr)
print(rounded_arr)

[-2. -3.  1.  4.  5.]


In [ ]:
#30. How to find common values between two arrays?


In [61]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])
common_values=np.intersect1d(arr1,arr2)
print(common_values)

[3 4 5]
